-- Run this in Supabase SQL Editor to create report_sections and seed rows.
-- Table: id, section_name (unique), content_en, content_th

CREATE TABLE IF NOT EXISTS report_sections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_name text NOT NULL UNIQUE,
  content_en text,
  content_th text
);

INSERT INTO report_sections (section_name, content_en, content_th)
VALUES
  ('integrated_skills', NULL, NULL),
  ('wellness', NULL, NULL),
  ('strengths', NULL, NULL),
  ('future_plan', NULL, NULL),
  ('signature', NULL, NULL)
ON CONFLICT (section_name) DO NOTHING;

-- RLS: allow public read for report page; restrict write to authenticated.
ALTER TABLE report_sections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON report_sections FOR SELECT USING (true);
CREATE POLICY "Allow authenticated update" ON report_sections FOR ALL USING (auth.role() = 'authenticated');
